GET http://localhost:5274/games

###
GET http://localhost:5274/games/1

###
POST http://localhost:5274/games
Content-Type: application/json

{
    "name": "Final Fantasy XIV",
    "genreId": 2,
    "price": 59.99,
    "releaseDate": "2010-09-30"
}

###
PUT http://localhost:5274/games/3
Content-Type: application/json

{
    "name": "Street Fighter II Turbo",
    "genreId": 1,
    "price": 19.99,
    "releaseDate": "1991-02-01"
}

###
DELETE http://localhost:5274/games/8